import React from "react";
import { Layout, Row, Col, Button, message, Input, Menu, Tag } from "antd";

class MenuList extends React.Component {
    render() {
        return (
            <Row className={"tools"}>
                <Col span={24}>
                    <Menu
                        mode="horizontal"
                    >
                        <Menu.SubMenu
                            title="Point"
                        >
                            <Menu.ItemGroup
                                title={"Point"}
                            >
                                <Menu.Item
                                    key={"index"}
                                >
                                    <a
                                        href={"/pointTable/0"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Index</a>
                                </Menu.Item>
                                <Menu.Item
                                    key={"report"}
                                >
                                    <a
                                        href={"/report"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Report</a>
                                </Menu.Item>
                                <Menu.Item
                                    key={"summary"}
                                >
                                    <a
                                        href={"/summary/points/0"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Summary</a>
                                </Menu.Item>
                                <Menu.Item
                                    key={"willing"}
                                >
                                    <a
                                        href={"/willing"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Willing</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                            <Menu.ItemGroup
                                title={"Summary"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/PointSummary"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Index</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                        </Menu.SubMenu>
                        <Menu.SubMenu
                            title={"Work"}
                        >
                            <Menu.ItemGroup
                                title={"GTD"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/GTD"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Index</a>
                                </Menu.Item>
                                <Menu.Item>
                                    <a
                                        href={"/GTDHistory"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >History</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                            <Menu.ItemGroup
                                title={"Clock"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/clock_in"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Work Time</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                        </Menu.SubMenu>
                        <Menu.SubMenu
                            title={"Game"}
                        >
                            <Menu.ItemGroup
                                title={"Fate"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/Decision"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Choice</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                            <Menu.ItemGroup
                                title={"Psychotherapy"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/Psychotherapy/CheckList"}
                                        target={"_blank"}
                                        rel={"noreferrer"}
                                    >
                                        Me
                                    </a>
                                </Menu.Item>
                                <Menu.Item>
                                    <a
                                        href={"/Psychotherapy/CheckListHistory"}
                                        target={"_blank"}
                                        rel={"noreferrer"}
                                    >
                                        History
                                    </a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                        </Menu.SubMenu>
                        <Menu.SubMenu
                            title={"Schedule"}
                        >
                            <Menu.ItemGroup
                                title={"OKR"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/OKR"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >
                                        Index
                                    </a>
                                </Menu.Item>
                                <Menu.Item>
                                    <a
                                        href={"/Actions"}
                                        target={"_blank"}
                                        rel={"noreferrer"}
                                    >
                                        Actions
                                    </a>
                                </Menu.Item>
                                <Menu.Item>
                                    <a
                                        href={"/ActionSummary"}
                                        target={"_blank"}
                                        rel={"noreferrer"}
                                    >
                                        Actions Summary
                                    </a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                            <Menu.ItemGroup
                                title={"Plan"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/planTable"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Plans</a>
                                </Menu.Item>
                                <Menu.Item>
                                    <a
                                        href={"/plan"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Calendar</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                        </Menu.SubMenu>
                        <Menu.SubMenu
                            title={"Tools"}
                        >
                            <Menu.ItemGroup
                                title={"Common"}
                            >
                                <Menu.Item>
                                    <a
                                        href={"/image"}
                                        target={"_blank"}
                                        rel="noreferrer"
                                    >Image Upload</a>
                                </Menu.Item>
                            </Menu.ItemGroup>
                        </Menu.SubMenu>
                    </Menu>
                </Col>
            </Row>
        )
    }
}

export default MenuList;
